### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LukeOnuke** [ErdbeerbaerLP/DiscordRichPresence#20]
**What happened?**
- Mod requires that it has iteslf on the server, but when put on the server it poorly manages serverside.

**What should happen?**
- Either the mod would not require to have itself on the server, or it should detect that its on a server and should not use client classes.

**Steps to reproduce**
- Add discord rpc, start dedicated server without it.
- Try to connect throught the server list (NOT DIRECT CONNECT)

**Version**
1.16

Mod version _2.0.7_

**Config file**
```toml

#Discord RichPresence Config File
[Rich-Presence]
	#First line of Rich Presence
	Client-Name = "Beopack"
	#Do you want servers to send you a customized rich presence text?
	#Also toggles hardcoded custom icons and text of not fully integrated servers like mineplex
	Custom-Messages-From-Server = true
	#Placeholders:
	#%ip%  Server IP
	Server-Text = "Multiplayer"
	#Setting this to true disables name changing through GUI
	Disable-Name-changing = false
	#Do you want to use custom Hivemc integration (show what game you are playing)?
	Hivemc-Integration = true
	#Disables config GUI
	#Requires config file editing to enable again
	Disable-Config-GUI = false
	#Do you want to use custom Hypixel integration (show what game you are playing and such)?
	Hypixel-Integration = true
	#No placeholders supported, Text that shows when you are in the main menu
	Main-Menu = "In Main Menu"
	#Placeholders:
	#%coords% (X:??? Y:??? Z:???)
	#%world% World name
	Singleplayer-Text = "Playing in %world% (%coords%)"
	#Custom client id, see https://github.com/ErdbeerbaerLP/DiscordRichPresence/wiki/Set-up-custom-Icons-(for-Modpacks) for more info
	#Default: 511106082366554122
	client-id = "798088883313180703"
	#Do you want to print log of this mod to ingame chat?
	LogToChat = false
```
